import type {Metadata} from "next";
import "./globals.css";
import HeaderBar from "@/components/server/HeaderBar";
import FooterBar from "@/components/server/FooterBar";
import BlueprintEmptySpace from "@/components/server/BlueprintEmptySpace";
import SectionSpacer from "@/components/server/SectionSpacer";
import StoreProvider from "@/lib/contexts/StoreProvider";

export const metadata: Metadata = {
	title: "Michael bailey - Blog",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="h-full bg-gray-100">
		<body className="min-h-screen bg-blend-color-dodge">
		<StoreProvider>

			<div
				className="grid min-h-screen grid-rows-[min-content_2em_auto_2em_min-content] grid-cols-[2em_auto_2em]  lg:grid-cols-[10%_auto_10%] xl:grid-cols-[20%_auto_20%] ">

				<HeaderBar className="row-start-1 col-start-2 bg-background" />

				<SectionSpacer className="h-8 col-start-2 row-start-2" />

				<main className="row-start-3 col-start-2 p-auto">
					{children}
				</main>

				<FooterBar className="col-start-2 row-start-5" />

				<BlueprintEmptySpace className=" col-start-1 row-span-full" />
				<BlueprintEmptySpace className=" col-start-3 row-span-full" />

			</div>
		</StoreProvider>

		</body>

		</html>
	);
}
