services:
  postgres:
    image: postgres:16
    container_name: spring-blog-db
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  spring-blog-app:
    build:
      dockerfile: ./docker/local/Dockerfile
      context: .
    container_name: spring-blog-app
    ports:
      - "8484:8080"
    depends_on:
      - postgres
    environment:
      POSTGRES_URL: "jdbc:postgresql://postgres:5432/blogdb"
    env_file:
      - .env

volumes:
  pgdata:
