services:
  postgres:
    image: postgres:16
    container_name: spring-blog-db
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  spring-blog-app:
    build:
      context: ../
      dockerfile: ./backend/docker/Dockerfile
    container_name: spring-blog-app
    ports:
      - "8484:8080"
    depends_on:
      - postgres
    environment:
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
      POSTGRES_URL: "jdbc:postgresql://postgres:5432/blogdb"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      ALLOWED_HOSTS: "http://localhost:8485,http://localhost:8484"
      GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}

  next-blog-app:
    build:
      context: ../frontend
      dockerfile: ./docker/Dockerfile
    container_name: next-blog-app
    depends_on:
      - spring-blog-app
    ports:
      - "8485:3000"
    environment:
      HOST: 0.0.0.0
      NEXT_PUBLIC_API_HOSTNAME: http://spring-blog-app
      API_HOSTNAME: http://spring-blog-app

  nginx:
    image: nginx:latest
    container_name: spring-blog-nginx-dev
    ports:
      - "80:80"
    volumes:
      - ../default.local.conf:/etc/nginx/conf.d/default.conf

volumes:
  pgdata:
