services:
  postgres:
    image: postgres:16
    container_name: spring-blog-db
    user: 1001:1001
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data

  spring-blog-app:
    image: ghcr.io/michael-bailey/personal_website-backend:latest
    container_name: spring-blog-app
    ports:
      - "8484:8080"
    depends_on:
      - postgres
    environment:
      POSTGRES_URL: "jdbc:postgresql://postgres:5432/blogdb"
    env_file:
      - .env

  nextjs-blog-app:
    image: ghcr.io/michael-bailey/personal_website-frontend:latest
    container_name: next-blog-app
    ports:
      - "8485:3000"
    depends_on:
      - spring-blog-app
    environment:
      HOST: 0.0.0.0
      API_HOSTNAME: http://spring-blog-app

  nginx:
    image: nginx:latest
    container_name: spring-blog-nginx-dev
    ports:
      - "80:80"
    volumes:
      - ./default.dev.conf:/etc/nginx/conf.d/default.dev.conf